name: Test init-template script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  init-template:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check init-template.sh
      run: |
        ./init-template.sh my-test_app
